### PR TITLE
Capture current discussion on syntax in RecordDotSyntax

### PR DESCRIPTION
**Pull request by cdsmith**
I've tried to fairly capture current opinions from the discussion thread, but of course I will have failed.  I may have just missed some things, but I also sometimes have a sufficiently different point of view that it's hard for me to convincingly represent the other perspective. Happy to try to fix anything, or it can be fixed by others later.

I did not change the stated decision; just the reasons.

### CODE REVIEW

**Comment by cdsmith** [comment]
@tysonzero @chrisdone

**Comment by tysonzero** [comment]
> "But some would like to resist spreading this generalization further."

I would specifically mention that this would be the first section with the following properties:

1) The entire body of the section is an irreducible lexeme.

2) There is nothing operator-like within the section (previously you had either `,` or `::` or a regular operator).

3) Parenthesis are not required to make parsing work.

> and has its own challenges around how to handle nested fields like `.foo.bar`, how to desugar `x {foo.bar = 42}` consistently, and so on.

There are a variety of ways to handle nested fields, such as using `>>>` , and `{foo.bar = 42}` would be handled separately. I would drop think section, we'll have that discussion if and when needed.

> * Some consider it acceptable (if unfortunate) that `a . b` and `a.b` have different meanings, but believe that assigning three distinct meanings to `a . b`, `a .b`, and `a.b` is just too confusing.

It's worth mentioning that either way `(. b)` or `( . b)` and `(.b)` or `( .b)` will have distinct meanings. So there is still a change in meaning based solely on adding a ` ` after the `.` either way.

**Comment by cdsmith** [comment]
@tysonzero 

Thanks.  I made some changes.

I'm still not sure why "an irreducible lexeme" matters, but I'm guessing it's because it makes it look more like a binary operator to you.  I explained it that way, but feel free to tell me if I'm wrong.  I mentioned point 3 in the pragmatics section, since it doesn't seem to affect whether it's a section or not, so much as whether parentheses should be required even if it's not a section.

Good point about dropping the speculation on `.foo` as a generic label.  I don't think this makes the problem go away, though, so this is not replaced with more detail on desugaring nested fields in the current proposal.  This actually raised a small question about `RebindableSyntax` that would be good to answer.

I haven't made the last change, because I'm still trying to understand.

**Comment by tysonzero** [comment]
Hmm ok if it’s alright with you I’m probably going to rewrite some of the arguments in favor of `.foo`. The current word choice comes off quite skewed.

**Comment by tysonzero** [comment]
What I’m trying to get at with the last point is that no matter what we do `.x` and `. x` are going to have different meanings. There will always be a case where both `.x` and `. x` both compile but de different things. 

It’s just that with the required parenthesis you can try and minimizes the number of situations in which they both compile, but the underlying difference can never be truly avoided.

**Comment by cdsmith** [comment]
@tysonzero Definitely okay with me.  This is absolutely not well written, and I hate the "Some say this..." language.  I did do my best to capture your perspective, but I'm also trying to keep this concise and focused on the important substantive issues (something I haven't succeeded at yet), so I'm resisting just tossing in lists of text.  Feel free to send me a pull request, or you can always just send your own pull request to the proposal.  I'm no kind of authority here.

**Comment by ndmitchell** [comment]
Thanks so much, this is great stuff - I appreciate you taking the time to write it.

**Comment by tysonzero** [comment]
Sorry I ended up being more busy than expected, I would still like to further clarify some of this, will try to do so soon.

**Pull request merged**
